"""add session violations table and terminated status

Revision ID: d2e5a307c816
Revises: 8c2144564bce
Create Date: 2026-06-30 06:25:50.458532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2e5a307c816'
down_revision: Union[str, Sequence[str], None] = '8c2144564bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE sessionstatus ADD VALUE IF NOT EXISTS 'terminated'")
    op.create_table('session_violations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('violation_type', sa.Enum('fullscreen_exit', 'tab_switch', 'window_blur', 'copy_attempt', 'cut_attempt', 'paste_attempt', 'context_menu', name='violationtype'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_violations')
    # ### end Alembic commands ###