import { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import Button from "../components/ui/Button";
import { Input } from "../components/ui/Input";

export default function Login() {
  const [form,     setForm]     = useState({ email: "", password: "" });
  const [error,    setError]    = useState("");
  const [loading,  setLoading]  = useState(false);
  const [capsLock, setCapsLock] = useState(false);
  const { login }  = useAuth();
  const navigate   = useNavigate();

  const handleChange = (e) =>
    setForm((f) => ({ ...f, [e.target.name]: e.target.value }));

  const handleKeyDown = (e) =>
    setCapsLock(e.getModifierState?.("CapsLock") ?? false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError("");
    setLoading(true);
    try {
      await login(form.email, form.password);
      navigate("/dashboard");
    } catch (err) {
      const status = err.response?.status;
      if (status === 429) {
        setError("Too many login attempts. Please wait a minute and try again.");
      } else {
        setError(err.response?.data?.detail || "Login failed. Please check your credentials.");
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ minHeight: "100vh", display: "flex", background: "#111827" }}>
      {/* Left panel */}
      <div style={{
        width: 420, flexShrink: 0,
        background: "linear-gradient(135deg, #1e1b4b 0%, #111827 100%)",
        display: "flex", flexDirection: "column", justifyContent: "center",
        padding: "48px 40px", borderRight: "1px solid #1f2937",
      }}>
        <div style={{ marginBottom: 48 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 32 }}>
            <div style={{ width: 36, height: 36, borderRadius: 8, background: "#6366f1", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 18 }}>🎯</div>
            <span style={{ fontSize: 18, fontWeight: 700, color: "#f9fafb" }}>AI Mock Interview</span>
          </div>
          <h1 style={{ fontSize: 28, fontWeight: 700, color: "#f9fafb", margin: "0 0 12px" }}>
            Prepare smarter.<br />Interview better.
          </h1>
          <p style={{ color: "#6b7280", fontSize: 14, lineHeight: 1.7, margin: 0 }}>
            AI-powered mock interviews tailored to your role, with real-time feedback and analytics to track your progress.
          </p>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          {[
            ["🤖", "AI Question Generation", "Role-specific questions generated by Gemini AI"],
            ["🎤", "Voice Interviews",        "Answer using your voice with live transcription"],
            ["📊", "Performance Analytics",  "Track improvement across sessions with charts"],
          ].map(([icon, title, desc]) => (
            <div key={title} style={{ display: "flex", gap: 12, alignItems: "flex-start" }}>
              <span style={{ fontSize: 18, flexShrink: 0, marginTop: 2 }}>{icon}</span>
              <div>
                <p style={{ color: "#e5e7eb", fontSize: 14, fontWeight: 500, margin: "0 0 2px" }}>{title}</p>
                <p style={{ color: "#6b7280", fontSize: 12, margin: 0 }}>{desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Right panel */}
      <div style={{ flex: 1, display: "flex", alignItems: "center", justifyContent: "center", padding: 32 }}>
        <div className="page-enter" style={{ width: "100%", maxWidth: 380 }}>
          <h2 style={{ fontSize: 24, fontWeight: 700, margin: "0 0 6px" }}>Welcome back</h2>
          <p style={{ color: "#6b7280", fontSize: 14, margin: "0 0 28px" }}>
            Don't have an account?{" "}
            <Link to="/register" style={{ color: "#818cf8", textDecoration: "none", fontWeight: 500 }}>Sign up</Link>
          </p>

          {error && (
            <div style={{ background: "rgba(239,68,68,0.1)", border: "1px solid rgba(239,68,68,0.3)", borderRadius: 8, padding: "10px 14px", marginBottom: 20 }}>
              <p style={{ color: "#f87171", fontSize: 13, margin: 0 }}>{error}</p>
            </div>
          )}

          <form onSubmit={handleSubmit} style={{ display: "flex", flexDirection: "column", gap: 16 }}>
            <Input
              name="email" type="email" label="Email"
              placeholder="you@example.com"
              value={form.email} onChange={handleChange} required
            />

            <div>
              <Input
                name="password" type="password" label="Password"
                placeholder="••••••••"
                value={form.password}
                onChange={handleChange}
                onKeyDown={handleKeyDown}
                required
              />
              {capsLock && (
                <p style={{ color: "#f59e0b", fontSize: 12, margin: "6px 0 0", display: "flex", alignItems: "center", gap: 4 }}>
                  ⚠ Caps Lock is on
                </p>
              )}
            </div>

            <div style={{ textAlign: "right", marginTop: -8 }}>
              <Link to="/forgot-password" style={{ color: "#6b7280", fontSize: 13, textDecoration: "none" }}
                onMouseEnter={e => e.target.style.color = "#818cf8"}
                onMouseLeave={e => e.target.style.color = "#6b7280"}>
                Forgot password?
              </Link>
            </div>

            <Button type="submit" fullWidth loading={loading} size="lg">
              {loading ? "Signing in..." : "Sign In"}
            </Button>
          </form>
        </div>
      </div>
    </div>
  );
}